name: landbase_ai_suite_development

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env.development
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mattermost:
    image: mattermost/mattermost-team-edition:${MATTERMOST_VERSION}
    env_file:
      - .env.development
    ports:
      - "${MATTERMOST_PORT}:8065"
    volumes:
      - mattermost_data:/mattermost
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    env_file:
      - .env.development
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
      target: development
      args:
        - RUBY_VERSION=${RUBY_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - YARN_VERSION=${YARN_VERSION}
        - RAILS_VERSION=${RAILS_VERSION}
    env_file:
      - .env.development
    ports:
      - "${RAILS_PORT}:3000"
    volumes:
      - ./${RAILS_APP_NAME}:/${RAILS_APP_NAME}
      - bundle_cache:/usr/local/bundle
      - yarn_global_cache:/root/.yarn/berry/cache
    command: >
      bash -c "
        cd /${RAILS_APP_NAME} &&
        bin/dev
      "
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
      target: development
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NEXTJS_VERSION=${NEXTJS_VERSION}
    env_file:
      - .env.development
    ports:
      - "${NEXTJS_PORT}:3000"
    volumes:
      - ./${NEXTJS_APP_NAME}:/app/${NEXTJS_APP_NAME}
      - nextjs_node_modules:/app/${NEXTJS_APP_NAME}/node_modules
    command: >
      bash -c "
        cd /app/${NEXTJS_APP_NAME} &&
        npm run dev
      "
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local
  mattermost_data:
    driver: local
  n8n_data:
    driver: local
  bundle_cache:
    driver: local
  yarn_global_cache:
    driver: local
  nextjs_node_modules:
    driver: local
