name: landbase_ai_suite

services:
  db-suite:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env.development
      - .env.local
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mattermost:
    image: mattermost/mattermost-team-edition:${MATTERMOST_VERSION}
    env_file:
      - .env.development
      - .env.local
    ports:
      - "8065:8065"
    volumes:
      - mattermost_config:/mattermost/config
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client_plugins:/mattermost/client/plugins
    depends_on:
      db-suite:
        condition: service_healthy

  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    env_file:
      - .env.development
      - .env.local
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      db-suite:
        condition: service_healthy

  platform:
    build:
      context: ./rails
      dockerfile: Dockerfile.platform
      target: development
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        RAILS_VERSION: ${RAILS_VERSION}
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bin/dev"
    volumes:
      - ./rails/platform:/platform
      - platform_bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env.development
      - .env.local
    depends_on:
      db-suite:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local
  mattermost_config:
    driver: local
  mattermost_data:
    driver: local
  mattermost_logs:
    driver: local
  mattermost_plugins:
    driver: local
  mattermost_client_plugins:
    driver: local
  n8n_data:
    driver: local
  platform_bundle_cache:
    driver: local
