name: landbase_ai_suite

services:
  db-suite:
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env.production
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  platform:
    build:
      context: ./rails
      dockerfile: Dockerfile.platform
      target: production
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        RAILS_VERSION: ${RAILS_VERSION}
    env_file:
      - .env.production
      - .env.local
    expose:
      - "3000"
    depends_on:
      db-suite:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - internal
      - web-proxy-net
    restart: unless-stopped

networks:
  internal:
    internal: true
  web-proxy-net:
    external: true

volumes:
  postgres_data:
